### ISSUE TITLE
Crash in strarray_find_dest related to fix for #997

### ISSUE THREAD

**Issue by josephbisch** [irssi/irssi#1002]
Because dest->target is NULL and is used as a parameter to `g_ascii_strcasecmp` in `strarray_find_dest`.

```
(process:8842): GLib-CRITICAL (recursed) **: g_ascii_strcasecmp: assertion 's1 != NULL' failed
Thread 1 "irssi" received signal SIGABRT, Aborted.
0x00007ffff741dd7f in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff741dd7f in raise () from /usr/lib/libc.so.6
#1  0x00007ffff7408672 in abort () from /usr/lib/libc.so.6
#2  0x00007ffff79bc04e in ?? () from /usr/lib/libglib-2.0.so.0
#3  0x00007ffff79fd5e3 in g_logv () from /usr/lib/libglib-2.0.so.0
#4  0x00007ffff79fd7e0 in g_log () from /usr/lib/libglib-2.0.so.0
#5  0x00007ffff79e162b in g_ascii_strcasecmp () from /usr/lib/libglib-2.0.so.0
#6  0x000055555589377f in window_item_find_window (window=0x60e000000ba0, server=0x0, name=0x0) at window-items.c:220
#7  0x000055555582fe10 in strarray_find_dest (array=0x602000072710, dest=0x7fffffffbc00) at fe-common-core.c:487
#8  0x000055555588abbd in sig_hilight_text (dest=0x7fffffffbc00, msg=0x60800001aea0 "\004\071/-\004g!\004\071/-\004g \004cIrssi:\004c \004</critical\004g g_ascii_strcasecmp: assertion 's1 != NULL' failed") at window-activity.c:91
#9  0x000055555597c8e8 in signal_emit_real (rec=0x603000032a10, params=3, va=0x7fffffffb580, first_hook=0x604000017950) at signals.c:242
#10 0x000055555597d17d in signal_emit_id (signal_id=307, params=3) at signals.c:304
#11 0x0000555555874a91 in print_line (dest=0x7fffffffbc00, text=0x60600003e960 "\004</critical\004g g_ascii_strcasecmp: assertion 's1 != NULL' failed") at printtext.c:182
#12 0x00005555558747e7 in printformat_module_dest_charargs (module=0x555555a00ee0 <.str.15> "fe-common/core", dest=0x7fffffffbc00, formatnum=215, arglist=0x7fffffffb980) at printtext.c:80
#13 0x00005555558744df in printformat_module_dest_args (module=0x555555a00ee0 <.str.15> "fe-common/core", dest=0x7fffffffbc00, formatnum=215, va=0x7fffffffbda0) at printtext.c:58
#14 0x0000555555875042 in printformat_module_args (module=0x555555a00ee0 <.str.15> "fe-common/core", server=0x0, target=0x0, level=1048576, formatnum=215, va=0x7fffffffbda0) at printtext.c:101
#15 0x000055555587538f in printformat_module (module=0x555555a00ee0 <.str.15> "fe-common/core", server=0x0, target=0x0, level=1048576, formatnum=215) at printtext.c:110
#16 0x000055555582f023 in glog_func (log_domain=0x7ffff7a3f0d6 "GLib", log_level=G_LOG_LEVEL_CRITICAL, message=0x60600003e8a0 "g_ascii_strcasecmp: assertion 's1 != NULL' failed") at fe-common-core.c:277
#17 0x00007ffff79fd5c1 in g_logv () from /usr/lib/libglib-2.0.so.0
#18 0x00007ffff79fd7e0 in g_log () from /usr/lib/libglib-2.0.so.0
#19 0x00007ffff79e162b in g_ascii_strcasecmp () from /usr/lib/libglib-2.0.so.0
#20 0x000055555589377f in window_item_find_window (window=0x60e000000ba0, server=0x622000001900, name=0x0) at window-items.c:220
#21 0x000055555582fe10 in strarray_find_dest (array=0x602000072710, dest=0x7fffffffcd00) at fe-common-core.c:487
#22 0x000055555588abbd in sig_hilight_text (dest=0x7fffffffcd00, msg=0x6030000890e0 "\004\071/-\004g!\004\071/-\004g WALLjoseWʲh") at window-activity.c:91
#23 0x000055555597c8e8 in signal_emit_real (rec=0x603000032a10, params=3, va=0x7fffffffc960, first_hook=0x604000017950) at signals.c:242
#24 0x000055555597d17d in signal_emit_id (signal_id=307, params=3) at signals.c:304
#25 0x0000555555874a91 in print_line (dest=0x7fffffffcd00, text=0x6020001568b0 "WALLjoseWʲh") at printtext.c:182
#26 0x0000555555876500 in printtext_dest_args (dest=0x7fffffffcd00, text=0x5555559f4da0 <.str.44> "%s", va=0x7fffffffcd70) at printtext.c:316
#27 0x0000555555876822 in printtext (server=0x622000001900, target=0x0, level=1, text=0x5555559f4da0 <.str.44> "%s") at printtext.c:340
#28 0x00005555557ffe5a in event_received (server=0x622000001900, data=0x611000012b03 "WALLjoseWʲh", nick=0x611000012b01 "h", addr=0x0) at fe-events.c:430
#29 0x000055555597c8e8 in signal_emit_real (rec=0x603000044080, params=4, va=0x7fffffffd3a0, first_hook=0x604000019550) at signals.c:242
#30 0x000055555597d17d in signal_emit_id (signal_id=206, params=4) at signals.c:304
#31 0x00005555558a5629 in irc_server_event (server=0x622000001900, line=0x611000012b03 "WALLjoseWʲh", nick=0x611000012b01 "h", address=0x0) at irc.c:339
#32 0x000055555597c8e8 in signal_emit_real (rec=0x603000014770, params=4, va=0x7fffffffda00, first_hook=0x604000011090) at signals.c:242
#33 0x000055555597d17d in signal_emit_id (signal_id=96, params=4) at signals.c:304
#34 0x00005555558a5a74 in irc_parse_incoming_line (server=0x622000001900, line=0x611000012b03 "WALLjoseWʲh") at irc.c:392
#35 0x000055555597c8e8 in signal_emit_real (rec=0x6030000179e0, params=2, va=0x7fffffffe100, first_hook=0x604000011110) at signals.c:242
#36 0x000055555597d17d in signal_emit_id (signal_id=205, params=2) at signals.c:304
#37 0x00005555558a5e6c in irc_parse_incoming (server=0x622000001900) at irc.c:413
#38 0x0000555555942408 in irssi_io_invoke (source=0x60c00002d340, condition=G_IO_IN, data=0x603000084220) at misc.c:51
#39 0x00007ffff7a0c8d1 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#40 0x00007ffff7a0e5e9 in ?? () from /usr/lib/libglib-2.0.so.0
#41 0x00007ffff7a0e62e in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#42 0x00005555557e88f7 in main (argc=2, argv=0x7fffffffe788) at irssi.c:346
```

Reproducer (with INPUT command):
```
echo -n $'001\nINPUT /join #chan\nINPUT /window new -right\nINPUT /window right -directional\nINPUT /window level all\nINPUT /window up\nANYTHING\n' | nc -l -p 6667
```

Reproducer (without INPUT command):
```
(echo -n $'001\n'; yes) | nc -l -p 6667
```
Then, meanwhile, in irssi:
```
/connect localhost
/join #chan 
/window new -right
/window right -directional
/window level all
/window up
```

**Comment by ailin-nemui** [comment]
#997
