### ISSUE TITLE
Crash under heavy spam with linked list corruption

### ISSUE THREAD

**Issue by linabeee** [irssi/irssi#1333]
I was connected to a server that was undergoing a _lot_ of spam and irssi abruptly crashed and wrote something that looked like (paraphrasing) "anmalloc: linked list corruption". coredump is attached: [core.irssi.1000.cdb709653fb24bac964666f9203e17f8.6826.1623761751000000.gz](https://github.com/irssi/irssi/files/6656416/core.irssi.1000.cdb709653fb24bac964666f9203e17f8.6826.1623761751000000.gz)

Unfortunately the platform under which this happened is NixOS, which throws away symbols on build. I have tried to make a debug build with usable symbols, haven't succeeded :/

**Comment by linabeee** [comment]
I have a non-stripped backtrace made by evaluating `(import <nixpkgs> {}).irssi.overrideAttrs (_: { dontStrip = true; })`:
```
#0  0x00007f7d5f00e33a in raise () from /nix/store/ikl21vjfq900ccbqg1xasp83kadw6q8y-glibc-2.32-46/lib/libc.so.6
No symbol table info available.
#1  0x00007f7d5eff8523 in abort () from /nix/store/ikl21vjfq900ccbqg1xasp83kadw6q8y-glibc-2.32-46/lib/libc.so.6
No symbol table info available.
#2  0x00007f7d5f04e958 in __libc_message () from /nix/store/ikl21vjfq900ccbqg1xasp83kadw6q8y-glibc-2.32-46/lib/libc.so.6
No symbol table info available.
#3  0x00007f7d5f05612a in malloc_printerr () from /nix/store/ikl21vjfq900ccbqg1xasp83kadw6q8y-glibc-2.32-46/lib/libc.so.6
No symbol table info available.
#4  0x00007f7d5f0597a4 in _int_malloc () from /nix/store/ikl21vjfq900ccbqg1xasp83kadw6q8y-glibc-2.32-46/lib/libc.so.6
No symbol table info available.
#5  0x00007f7d5f05a2ef in _int_realloc () from /nix/store/ikl21vjfq900ccbqg1xasp83kadw6q8y-glibc-2.32-46/lib/libc.so.6
No symbol table info available.
#6  0x00007f7d5f05b597 in realloc () from /nix/store/ikl21vjfq900ccbqg1xasp83kadw6q8y-glibc-2.32-46/lib/libc.so.6
No symbol table info available.
#7  0x00007f7d5f6074f8 in g_realloc () from /nix/store/24lgqdbdzy31k0i2dh6s51g2ayy6cpyl-glib-2.68.2/lib/libglib-2.0.so.0
No symbol table info available.
#8  0x00007f7d5f624996 in g_string_insert_c () from /nix/store/24lgqdbdzy31k0i2dh6s51g2ayy6cpyl-glib-2.68.2/lib/libglib-2.0.so.0
No symbol table info available.
#9  0x000000000045d98f in g_string_append_c_inline (c=<optimized out>, gstring=0x169b180) at /nix/store/fp0r3qz04wq4gx4jar1cp5xn9cm834n4-glib-2.68.2-dev/include/glib-2.0/glib/gstring.h:175
No locals.
#10 format_get_text_args (arglist=0x7ffd10dc1ea0, text=<optimized out>, dest=0x7ffd10dc1ff0) at formats.c:602
        ret = <optimized out>
        need_free = 1
        adv = <optimized out>
        out = 0x169b180
        code = 0 '\000'
        out = <optimized out>
        code = <optimized out>
        ret = <optimized out>
        need_free = <optimized out>
        adv = <optimized out>
        ret = <optimized out>
        diff = <optimized out>
        len = <optimized out>
#11 format_get_text_theme_charargs (theme=theme@entry=0x142ed50, module=module@entry=0x4c12a5 "fe-common/core", dest=dest@entry=0x7ffd10dc1ff0, formatnum=formatnum@entry=66, 
    args=args@entry=0x7ffd10dc1ea0) at formats.c:658
        module_theme = 0x7ffd10dc1e0c
        text = <optimized out>
#12 0x0000000000463789 in printformat_module_dest_charargs (module=0x4c12a5 "fe-common/core", dest=0x7ffd10dc1ff0, formatnum=66, arglist=0x7ffd10dc1ea0) at printtext.c:78
        theme = 0x142ed50
        str = <optimized out>
#13 0x000000000046389a in printformat_module_dest_args (module=module@entry=0x4c12a5 "fe-common/core", dest=dest@entry=0x7ffd10dc1ff0, formatnum=formatnum@entry=66, 
    va=va@entry=0x7ffd10dc2070) at printtext.c:58
        arglist = {0x16baa91 "Afootpluto", 0x16baa9c "Afootpluto@Clk-54931D6.sub-174-196-11.myvzw.com", 0x1974970 "Quit: Leaving", 0x1972fb0 "#fn-freenode", 0x0, 
          0x50b198 <mainconfig> "p\346?\001", 0x1acb7b0 "\324\002", 0x1972fb0 "#fn-freenode", 0x16c5000 "\320\002", 
          0x4b1c15 <config_node_find+101> "\205\300t\fH\213[\bH\205\333u\336E1\344L\211\340[]A\\\303\017\037"}
        buffer = "\300\263@\001\000\000\000\000p$D\001\000\000\000\000\230\261P\000\000\000\000\000\370\034K\000\000\000\000\000\361\264L", '\000' <repeats 13 times>, "\361\264L\000\000\000\000\000\025\034K", '\000' <repeats 14 times>, "\002", '\000' <repeats 14 times>, "\016#K", '\000' <repeats 13 times>, "o#K\000\000\000\000\000@\372h\001\000\000\000\000@\372h\001\000\000\000\000\000\002\000\000\000\000\000\000\313\310F\000\000\000\000\000\360\037\334\020\375\177\000\000\360\037\334\020\375\177\000\000\260\267\254\001", '\000' <repeats 12 times>, "\260/\227\001\000\000\000\000\000\002\000\000\000\000\000\000\000Pl\001\000\000\000"
        formats = <optimized out>
#14 0x00000000004639c3 in printformat_module_args (module=0x4c12a5 "fe-common/core", server=<optimized out>, target=<optimized out>, level=<optimized out>, formatnum=66, va=va@entry=0x7ffd10dc2070) at printtext.c:101
        dest = {window = 0x168fa40, server = 0x1acb7b0, server_tag = 0x197e000 "pissnet", target = 0x1972fb0 "#fn-freenode", nick = 0x0, address = 0x0, level = 512, hilight_priority = 0, hilight_color = 0x0, flags = 0}
#15 0x0000000000463a75 in printformat_module (module=module@entry=0x4c12a5 "fe-common/core", server=server@entry=0x1acb7b0, target=<optimized out>, level=<optimized out>, formatnum=formatnum@entry=66) at printtext.c:110
        va = {{gp_offset = 48, fp_offset = 48, overflow_arg_area = 0x7ffd10dc2168, reg_save_area = 0x7ffd10dc2090}}
#16 0x0000000000456021 in sig_message_quit (server=0x1acb7b0, nick=0x16baa91 "Afootpluto", address=0x16baa9c "Afootpluto@Clk-54931D6.sub-174-196-11.myvzw.com", reason=0x1974970 "Quit: Leaving") at fe-messages.c:415
        rec = 0x16c5000
        window = 0x168fa40
        chans = 0x169a1a0
        tmp = 0x1689a10
        windows = <optimized out>
        print_channel = 0x1972fb0 "#fn-freenode"
        once = 0
        count = <optimized out>
        level = 512
#17 0x00000000004ab160 in signal_emit_real (rec=rec@entry=0x1448b60, params=params@entry=4, va=va@entry=0x7ffd10dc2280, first_hook=<optimized out>) at signals.c:242
        arglist = {0x1acb7b0, 0x16baa91, 0x16baa9c, 0x1974970, 0x0, 0x0}
        prev_emitted_signal = 0x141c360
        hook = 0x1448b90
        prev_emitted_hook = 0x147ebd0
        i = <optimized out>
        stopped = 0
        stop_emit_count = 0
        continue_emit_count = 0
        __func__ = "signal_emit_real"
#18 0x00000000004ab70d in signal_emit (signal=signal@entry=0x4c1864 "message quit", params=params@entry=4) at signals.c:286
        rec = 0x1448b60
        va = {{gp_offset = 48, fp_offset = 48, overflow_arg_area = 0x7ffd10dc2370, reg_save_area = 0x7ffd10dc22a0}}
        signal_id = <optimized out>
        __func__ = "signal_emit"
#19 0x000000000043f0a4 in event_quit (server=0x1acb7b0, data=<optimized out>, nick=0x16baa91 "Afootpluto", addr=0x16baa9c "Afootpluto@Clk-54931D6.sub-174-196-11.myvzw.com") at fe-events.c:154
        recoded = 0x1974970 "Quit: Leaving"
        __func__ = "event_quit"
#20 0x00000000004ab160 in signal_emit_real (rec=rec@entry=0x141c360, params=params@entry=4, va=va@entry=0x7ffd10dc2430, first_hook=<optimized out>) at signals.c:242
        arglist = {0x1acb7b0, 0x19a9dcb, 0x16baa91, 0x16baa9c, 0x0, 0x0}
        prev_emitted_signal = 0x1418100
        hook = 0x147ebd0
        prev_emitted_hook = 0x1423fe0
        i = <optimized out>
        stopped = 0
        stop_emit_count = 0
        continue_emit_count = 0
        __func__ = "signal_emit_real"
#21 0x00000000004ab70d in signal_emit (signal=<optimized out>, params=params@entry=4) at signals.c:286
        rec = 0x141c360
        va = {{gp_offset = 48, fp_offset = 48, overflow_arg_area = 0x7ffd10dc2520, reg_save_area = 0x7ffd10dc2450}}
        signal_id = <optimized out>
        __func__ = "signal_emit"
#22 0x000000000046f4dd in irc_server_event (server=0x1acb7b0, line=0x16baacc "QUIT :Quit: Leaving", nick=0x16baa91 "Afootpluto", address=0x16baa9c "Afootpluto@Clk-54931D6.sub-174-196-11.myvzw.com") at irc.c:338
        signal = <optimized out>
        event = 0x19a9dc0 "event quit"
        args = <optimized out>
        __func__ = "irc_server_event"
#23 0x00000000004ab160 in signal_emit_real (rec=rec@entry=0x1418100, params=params@entry=4, va=va@entry=0x7ffd10dc2600, first_hook=<optimized out>) at signals.c:242
        arglist = {0x1acb7b0, 0x16baacc, 0x16baa91, 0x16baa9c, 0x0, 0x0}
        prev_emitted_signal = 0x1424040
        hook = 0x1423fe0
        prev_emitted_hook = 0x1424070
        i = <optimized out>
        stopped = 0
        stop_emit_count = 0
        continue_emit_count = 0
        __func__ = "signal_emit_real"
#24 0x00000000004ab7e5 in signal_emit_id (signal_id=<optimized out>, params=4) at signals.c:304
        rec = 0x1418100
        va = {{gp_offset = 48, fp_offset = 48, overflow_arg_area = 0x7ffd10dc26f0, reg_save_area = 0x7ffd10dc2620}}
        __func__ = "signal_emit_id"
#25 0x00000000004ab160 in signal_emit_real (rec=rec@entry=0x1424040, params=params@entry=2, va=va@entry=0x7ffd10dc2780, first_hook=<optimized out>) at signals.c:242
        arglist = {0x1acb7b0, 0x16baa90, 0x0, 0x0, 0x0, 0x0}
        prev_emitted_signal = 0x0
        hook = 0x1424070
        prev_emitted_hook = 0x0
        i = <optimized out>
        stopped = 0
        stop_emit_count = 0
        continue_emit_count = 0
        __func__ = "signal_emit_real"
#26 0x00000000004ab7e5 in signal_emit_id (signal_id=<optimized out>, params=params@entry=2) at signals.c:304
        rec = 0x1424040
        va = {{gp_offset = 32, fp_offset = 48, overflow_arg_area = 0x7ffd10dc2870, reg_save_area = 0x7ffd10dc27a0}}
        __func__ = "signal_emit_id"
#27 0x000000000046f655 in irc_parse_incoming (server=0x1acb7b0) at irc.c:413
        str = 0x16baa90 ":Afootpluto"
        count = 0
        ret = <optimized out>
        str = <optimized out>
        count = <optimized out>
        ret = <optimized out>
        __func__ = "irc_parse_incoming"
        _g_boolean_var_ = <optimized out>
#28 irc_parse_incoming (server=0x1acb7b0) at irc.c:396
        str = <optimized out>
        count = 0
        ret = 0
        __func__ = "irc_parse_incoming"
#29 0x000000000049c29e in irssi_io_invoke (source=<optimized out>, condition=<optimized out>, data=<optimized out>) at misc.c:51
        rec = <optimized out>
        icond = <optimized out>
#30 0x00007f7d5f6014af in g_main_context_dispatch () from /nix/store/24lgqdbdzy31k0i2dh6s51g2ayy6cpyl-glib-2.68.2/lib/libglib-2.0.so.0
No symbol table info available.
#31 0x00007f7d5f601858 in g_main_context_iterate.constprop () from /nix/store/24lgqdbdzy31k0i2dh6s51g2ayy6cpyl-glib-2.68.2/lib/libglib-2.0.so.0
No symbol table info available.
#32 0x00007f7d5f60190f in g_main_context_iteration () from /nix/store/24lgqdbdzy31k0i2dh6s51g2ayy6cpyl-glib-2.68.2/lib/libglib-2.0.so.0
No symbol table info available.
#33 0x000000000041d160 in main (argc=<optimized out>, argv=<optimized out>) at irssi.c:351
        version = 0
        options = {{long_name = 0x4c1726 "version", short_name = 118 'v', flags = 0, arg = G_OPTION_ARG_NONE, arg_data = 0x50a168 <version>, description = 0x4beb57 "Display Irssi version", arg_description = 0x0}, {long_name = 0x0, short_name = 0 '\000', flags = 0, arg = G_OPTION_ARG_NONE, arg_data = 0x0, description = 0x0, arg_description = 0x0}}
        loglev = <optimized out>
```
