### ISSUE TITLE
surprising crash without error msg when connect in startup

### ISSUE THREAD

**Issue by ailin-nemui** [irssi/irssi#1449]
```
$ irssi
[1] 19787 trace trap (core dumped)  irssi
```

`startup`
```
connect liberachat
```

backtrace
```
Program terminated with signal SIGTRAP, Trace/breakpoint trap.
#0  0x00007fcf0db4a332 in g_logv () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
(gdb) bt
#0  0x00007fcf0db4a332 in g_logv () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007fcf0db4a59f in g_log () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x000055d6e9d54cc6 in create_addr_conn (chat_type=-1, address=0x55d6ec19c970 "kreynet", port=0, chatnet=0x0, password=0x55d6ec19c977 "", 
    nick=0x55d6ec19c977 "", Python Exception <class 'gdb.error'> There is no member named keys.: 
optlist=0x55d6ec19bde0) at ../src/core/servers-setup.c:308
#3  0x000055d6e9d55054 in server_create_conn_opt (chat_type=-1, dest=0x55d6ec19c970 "kreynet", port=0, chatnet=0x0, password=0x55d6ec19c977 "", 
    nick=0x55d6ec19c977 "", Python Exception <class 'gdb.error'> There is no member named keys.: 
optlist=0x55d6ec19bde0) at ../src/core/servers-setup.c:405
#4  0x000055d6e9d4d0e6 in get_server_connect (data=0x55d6ec19d230 "kreynet", plus_addr=0x0, rawlog_file=0x7fffb0eb3ed8) at ../src/core/chat-commands.c:74
#5  0x000055d6e9d4d286 in cmd_connect (data=0x55d6ec19d230 "kreynet") at ../src/core/chat-commands.c:127
#6  0x000055d6e9d4915b in signal_emit_real (rec=0x55d6ebd75b80, params=3, va=0x7fffb0eb3fa8, first_hook=0x55d6ebd75bb0) at ../src/core/signals.c:242
#7  0x000055d6e9d493aa in signal_emit (signal=0x55d6ec1a2ff0 "command connect", params=3) at ../src/core/signals.c:286
#8  0x000055d6e9d33974 in parse_command (command=0x55d6ec1a9fc1 "connect kreynet", expand_aliases=1, server=0x0, item=0x0) at ../src/core/commands.c:920
#9  0x000055d6e9d33b0b in event_command (line=0x55d6ec1a9fc1 "connect kreynet", server=0x0, item=0x0) at ../src/core/commands.c:966
#10 0x000055d6e9d4915b in signal_emit_real (rec=0x55d6ebd74e10, params=3, va=0x7fffb0eb41f8, first_hook=0x55d6ebd9bd10) at ../src/core/signals.c:242
#11 0x000055d6e9d493aa in signal_emit (signal=0x55d6e9d9113d "D", params=3) at ../src/core/signals.c:286
#12 0x000055d6e9d4b166 in eval_special_string (cmd=0x55d6ebd789a0 "connect kreynet", data=0x55d6e9d93c5e "\373/\017\207\243\002", server=0x0, item=0x0)
    at ../src/core/special-vars.c:671
#13 0x000055d6e9d5c493 in autorun_startup () at ../src/fe-common/core/fe-common-core.c:490
#14 0x000055d6e9d5c5cd in fe_common_core_finish_init () at ../src/fe-common/core/fe-common-core.c:532
#15 0x000055d6e9d1afae in textui_finish_init () at ../src/fe-text/irssi.c:202
#16 0x000055d6e9d1b304 in main (argc=1, argv=0x7fffb0eb44e8) at ../src/fe-text/irssi.c:328
```

reported by `kinlo`

**Comment by josephbisch** [comment]
Steps to reproduce:

1. Create a file named startup in your Irssi home directory with contents like the following:
```
connect example
```
2. Start Irssi.
3. Crash happens immediately as the startup file attempts to run.
