### ISSUE TITLE
calling disconnect while in signal handler can crash irssi

### ISSUE THREAD

**Issue by ailin-nemui** [irssi/irssi#489]
sample report by @KindOne

```
Command: /trigger add -privmsgs -mask '*!*@*' -regex 'crash the irssi' -command 'disconnect' 

From another connection: /msg nick crash the irssi


sh-4.3$ irssi --version
irssi 0.8.20-g1a6ec1b (20160518 1657)

Program received signal SIGSEGV, Segmentation fault.
last_msg_add (list=0x0, nick=0x87e5dc1 "˒\267\070˒\267\270]~\b\270]~\be@freenude/topless/kindone", own=1, max=10)
    at chat-completion.c:95
95              rec = last_msg_find(*list, nick);
(gdb)

#0  last_msg_add (list=0x0, nick=0x87e5dc1 "˒\267\070˒\267\270]~\b\270]~\be@freenude/topless/kindone", own=1, max=10)
    at chat-completion.c:95
        rec = <optimized out>
#1  0x080d14e3 in signal_emit_real (rec=rec@entry=0x8179f50, params=params@entry=5, va=<optimized out>,
    va@entry=0xbffff288 "\330\070Z\b`s\303\b\301]~\b\311]~\b\210\025\210\b\274\362\377\277", first_hook=0x85b6028)
    at signals.c:242
        arglist = {0x85a38d8, 0x8c37360, 0x87e5dc1, 0x87e5dc9, 0x8881588, 0x0}
        prev_emitted_signal = 0x817d840
        hook = 0x818e150
        prev_emitted_hook = 0x819df48
        i = <optimized out>
        stopped = 0
        stop_emit_count = 0
        continue_emit_count = 0
        __func__ = "signal_emit_real"
#2  0x080d199b in signal_emit (signal=0x80e4ba9 "message private", params=5) at signals.c:286
        rec = 0x8179f50
        va = 0xbffff288 "\330\070Z\b`s\303\b\301]~\b\311]~\b\210\025\210\b\274\362\377\277"
        signal_id = <optimized out>
        __func__ = "signal_emit"
#3  0x080749ee in event_privmsg (server=0x85a38d8, data=0x8d65bf6 "KindOne :hack the irssi",
    nick=0x87e5dc1 "˒\267\070˒\267\270]~\b\270]~\be@freenude/topless/kindone",
    addr=0x87e5dc9 "]~\b\270]~\be@freenude/topless/kindone") at fe-events.c:68
        params = 0x8881588 "KindOne"
        target = 0x8881588 "KindOne"
        msg = 0x8881591 "hack the irssi"
        recoded = 0x8c37360 "hack the irssi"
        __func__ = "event_privmsg"
#4  0x080d14e3 in signal_emit_real (rec=rec@entry=0x817d840, params=params@entry=4, va=<optimized out>,
    va@entry=0xbffff378 "\330\070Z\b\366[\326\b\301]~\b\311]~\b", first_hook=0x819f038) at signals.c:242
        arglist = {0x85a38d8, 0x8d65bf6, 0x87e5dc1, 0x87e5dc9, 0x0, 0x0}
        prev_emitted_signal = 0x817ec10
        hook = 0x819df48
        prev_emitted_hook = 0x8184cb0
        i = <optimized out>
        stopped = 0
        stop_emit_count = 0
        continue_emit_count = 0
        __func__ = "signal_emit_real"
#5  0x080d199b in signal_emit (signal=0x8d65be8 "event privmsg", params=4) at signals.c:286
        rec = 0x817d840
        va = 0xbffff378 "\330\070Z\b\366[\326\b\301]~\b\311]~\b"
        signal_id = <optimized out>
        __func__ = "signal_emit"
#6  0x0809d4fb in irc_server_event (server=0x85a38d8, line=0x87e5deb "PRIVMSG KindOne :hack the irssi",
    nick=0x87e5dc1 "˒\267\070˒\267\270]~\b\270]~\be@freenude/topless/kindone",
    address=0x87e5dc9 "]~\b\270]~\be@freenude/topless/kindone") at irc.c:308
        signal = <optimized out>
        event = 0x8d65be8 "event privmsg"
        args = 0x8d65bf6 "KindOne :hack the irssi"
        __func__ = "irc_server_event"
#7  0x080d14e3 in signal_emit_real (rec=rec@entry=0x817ec10, params=params@entry=4, va=<optimized out>,
    va@entry=0xbffff458 "\330\070Z\b\353]~\b\301]~\b\311]~\b", first_hook=0x8184cb0) at signals.c:242
        arglist = {0x85a38d8, 0x87e5deb, 0x87e5dc1, 0x87e5dc9, 0x0, 0x0}
        prev_emitted_signal = 0x8184be0
        hook = 0x8184cb0
        prev_emitted_hook = 0x8184de8
        i = <optimized out>
        stopped = 0
        stop_emit_count = 0
        continue_emit_count = 0
        __func__ = "signal_emit_real"
#8  0x080d19f1 in signal_emit_id (signal_id=95, params=4) at signals.c:304
        rec = 0x817ec10
        va = 0xbffff458 "\330\070Z\b\353]~\b\301]~\b\311]~\b"
        __func__ = "signal_emit_id"
#9  0x0809d374 in irc_parse_incoming_line (server=0x85a38d8, line=<optimized out>) at irc.c:362
        nick = 0x87e5dc1 "˒\267\070˒\267\270]~\b\270]~\be@freenude/topless/kindone"
        address = 0x87e5dc9 "]~\b\270]~\be@freenude/topless/kindone"
        __func__ = "irc_parse_incoming_line"
#10 0x080d14e3 in signal_emit_real (rec=rec@entry=0x8184be0, params=params@entry=2, va=<optimized out>,
    va@entry=0xbffff518 "\330\070Z\b\300]~\b\330B[\b\300]~\b\001", first_hook=0x8184de8) at signals.c:242
        arglist = {0x85a38d8, 0x87e5dc0, 0x0, 0x0, 0x0, 0x0}
        prev_emitted_signal = 0x0
        hook = 0x8184de8
        prev_emitted_hook = 0x0
        i = <optimized out>
        stopped = 0
        stop_emit_count = 0
        continue_emit_count = 0
        __func__ = "signal_emit_real"
#11 0x080d19f1 in signal_emit_id (signal_id=203, params=2) at signals.c:304
        rec = 0x8184be0
        va = 0xbffff518 "\330\070Z\b\300]~\b\330B[\b\300]~\b\001"
        __func__ = "signal_emit_id"
#12 0x0809d674 in irc_parse_incoming (server=0x85a38d8) at irc.c:383
        str = 0x87e5dc0 "8˒\267\070˒\267\270]~\b\270]~\be@freenude/topless/kindone"
        count = 0
        ret = <optimized out>
        server = 0x85a38d8
        count = 0
        ret = 0
#13 0x080c41d8 in irssi_io_invoke (source=0x8227320, condition=G_IO_IN, data=0x854cfc8) at misc.c:54
        rec = 0x854cfc8
        icond = <optimized out>
#14 0xb7c5aa9e in g_io_unix_dispatch (source=0x87d7558, callback=0x80c4190 <irssi_io_invoke>, user_data=0x854cfc8)
    at /build/glib2.0-YzaC_a/glib2.0-2.48.1/./glib/giounix.c:165
        func = 0x80c4190 <irssi_io_invoke>
        watch = 0x87d7558
        buffer_condition = <optimized out>
#15 0xb7c13d8b in g_main_dispatch (context=0x8178680) at /build/glib2.0-YzaC_a/glib2.0-2.48.1/./glib/gmain.c:3154
        dispatch = 0xb7c5aa60 <g_io_unix_dispatch>
        prev_source = 0x0
        was_in_call = 0
        user_data = 0x854cfc8
        callback = 0x80c4190 <irssi_io_invoke>
        cb_funcs = <optimized out>
        cb_data = 0x85334f8
        need_destroy = <optimized out>
        source = 0x87d7558
        current = 0x81b6528
        i = 0
#16 g_main_context_dispatch (context=0x8178680) at /build/glib2.0-YzaC_a/glib2.0-2.48.1/./glib/gmain.c:3769
No locals.
#17 0xb7c14179 in g_main_context_iterate (context=context@entry=0x8178680, block=block@entry=1, dispatch=dispatch@entry=1,
    self=<optimized out>) at /build/glib2.0-YzaC_a/glib2.0-2.48.1/./glib/gmain.c:3840
        max_priority = 2147483647
        timeout = 893
        some_ready = 1
        nfds = 3
        allocated_nfds = <optimized out>
        fds = <optimized out>
#18 0xb7c14244 in g_main_context_iteration (context=0x8178680, may_block=1)
    at /build/glib2.0-YzaC_a/glib2.0-2.48.1/./glib/gmain.c:3901
        retval = <optimized out>
#19 0x0805a8a3 in main (argc=2, argv=0xbffff7c4) at irssi.c:336
        version = 0
        options = {{long_name = 0x80e2443 "dummy", short_name = 100 'd', flags = 0, arg = G_OPTION_ARG_NONE,
            arg_data = 0x8152cd8 <dummy>, description = 0x80e2449 "Use the dummy terminal mode", arg_description = 0x0}, {
            long_name = 0x80e4aaa "version", short_name = 118 'v', flags = 0, arg = G_OPTION_ARG_NONE,
            arg_data = 0x8152ccc <version>, description = 0x80e2465 "Display irssi version", arg_description = 0x0}, {
            long_name = 0x0, short_name = 0 '\000', flags = 0, arg = G_OPTION_ARG_NONE, arg_data = 0x0, description = 0x0,
            arg_description = 0x0}}
        loglev = <optimized out>

**Comment by ailin-nemui** [comment]
see also https://github.com/irssi/irssi/commit/124bcd48048762de9d17ff4f46df1cbfda9c1fb5 which was a consequence

**Comment by RealKindOne** [comment]
I think this issue can be closed. I just tested the lastest git commit and I have no crashes after multiple tests.

```
v1.5+1-dev-201-g465d3188-dirty
```

```
21:53:20 -!- Irssi: Disconnecting from server 127.0.0.1: [I've quit...]
21:53:20 -!- Irssi: Connection lost to 127.0.0.1
21:53:20 [nick(lol@10.10.1.2)] crash the irssi
```
