### ISSUE TITLE
Segfault in SSL code / sk_num

### ISSUE THREAD

**Issue by ailin-nemui** [irssi/irssi#750]
```
(gdb) bt
#0  0x00007f23d1777515 in sk_num () from /usr/lib64/libcrypto.so.1.0.0
#1  0x00007f23d17bc336 in X509_VERIFY_PARAM_set1_policies () from /usr/lib64/libcrypto.so.1.0.0
#2  0x00007f23d17bc730 in X509_VERIFY_PARAM_inherit () from /usr/lib64/libcrypto.so.1.0.0
#3  0x00007f23d17b5d2e in X509_STORE_CTX_init () from /usr/lib64/libcrypto.so.1.0.0
#4  0x00007f23d1b00aa8 in ssl_verify_cert_chain () from /usr/lib64/libssl.so.1.0.0
#5  0x00007f23d1adb51e in ssl3_get_server_certificate () from /usr/lib64/libssl.so.1.0.0
#6  0x00007f23d1ae0372 in ssl3_connect () from /usr/lib64/libssl.so.1.0.0
#7  0x00007f23d1aea12d in ssl23_connect () from /usr/lib64/libssl.so.1.0.0
#8  0x0000000000497af1 in irssi_ssl_handshake (handle=handle@entry=0x1801100) at network-openssl.c:795
#9  0x000000000048cd43 in server_connect_callback_init_ssl (server=0x1b63280, handle=0x1801100) at servers.c:176
#10 0x00000000004850dd in irssi_io_invoke (source=<optimized out>, condition=<optimized out>, data=<optimized out>) at misc.c:51
#11 0x00007f23d1d759e5 in g_main_dispatch (context=0x17f7b00) at gmain.c:3234
#12 g_main_context_dispatch (context=context@entry=0x17f7b00) at gmain.c:3899
#13 0x00007f23d1d75da8 in g_main_context_iterate (context=context@entry=0x17f7b00, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at gmain.c:3972
#14 0x00007f23d1d75e3c in g_main_context_iteration (context=0x17f7b00, context@entry=0x0, may_block=may_block@entry=1) at gmain.c:4033
#15 0x0000000000419c2b in main (argc=<optimized out>, argv=<optimized out>) at irssi.c:329
```

24ad8017

**Comment by ailin-nemui** [comment]
I used
```
/connect Freenode
/disconnect
/connect Freenode
```

@trasz could you see if you can identify anything, as this seems to be caused by the Capsicum code?

**Comment by trasz** [comment]
On 0911T0658, ailin-nemui wrote:
> I used
> ```
> /connect Freenode
> /disconnect
> /connect Freenode
> ```
> 
> @trasz could you see if you can identify anything, as this seems to be caused by the Capsicum code?

Sure.  Is this the binary built with capsicum support, or without?

**Comment by ailin-nemui** [comment]
TheLemonMan identified the issue, see #751
my build was without capsicum
