### ISSUE TITLE
Segfault when receiving privmsg

### ISSUE THREAD

**Issue by josephbisch** [irssi/irssi#826]
I'm pretty sure this is related to sideways splits.

```
ASAN:DEADLYSIGNAL
=================================================================
==28829==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000020 (pc 0x56416c93adbd bp 0x00000000000a sp 0x7ffedb6ef920 T0)
==28829==The signal is caused by a WRITE memory access.
==28829==Hint: address points to the zero page.
    #0 0x56416c93adbc in textbuffer_view_set_default_indent /home/joseph/git/irssi-sideways-split/src/fe-text/textbuffer-view.c:670:24
    #1 0x56416c9192f8 in gui_window_init /home/joseph/git/irssi-sideways-split/src/fe-text/gui-windows.c:48:2
    #2 0x56416c9189b6 in gui_window_created /home/joseph/git/irssi-sideways-split/src/fe-text/gui-windows.c:90:21
    #3 0x56416ca2242c in signal_emit_real /home/joseph/git/irssi-sideways-split/src/core/signals.c:242:3
    #4 0x56416ca21f9c in signal_emit /home/joseph/git/irssi-sideways-split/src/core/signals.c:286:3
    #5 0x56416c9a1ef1 in window_create /home/joseph/git/irssi-sideways-split/src/fe-common/core/fe-windows.c:130:2
    #6 0x56416c9a07a2 in window_item_create /home/joseph/git/irssi-sideways-split/src/fe-common/core/window-items.c:319:12
    #7 0x56416c97959b in signal_query_created /home/joseph/git/irssi-sideways-split/src/fe-common/core/fe-queries.c:67:3
    #8 0x56416ca2242c in signal_emit_real /home/joseph/git/irssi-sideways-split/src/core/signals.c:242:3
    #9 0x56416ca21f9c in signal_emit /home/joseph/git/irssi-sideways-split/src/core/signals.c:286:3
    #10 0x56416c9b935c in irc_query_create /home/joseph/git/irssi-sideways-split/src/irc/core/irc-queries.c:40:2
    #11 0x56416c97a085 in sig_message_private /home/joseph/git/irssi-sideways-split/src/fe-common/core/fe-queries.c:337:10
    #12 0x56416ca2242c in signal_emit_real /home/joseph/git/irssi-sideways-split/src/core/signals.c:242:3
    #13 0x56416ca21f9c in signal_emit /home/joseph/git/irssi-sideways-split/src/core/signals.c:286:3
    #14 0x56416c94ced3 in event_privmsg /home/joseph/git/irssi-sideways-split/src/fe-common/irc/fe-events.c
    #15 0x56416ca2242c in signal_emit_real /home/joseph/git/irssi-sideways-split/src/core/signals.c:242:3
    #16 0x56416ca21f9c in signal_emit /home/joseph/git/irssi-sideways-split/src/core/signals.c:286:3
    #17 0x56416c9aa596 in irc_server_event /home/joseph/git/irssi-sideways-split/src/irc/core/irc.c:338:7
    #18 0x56416ca2242c in signal_emit_real /home/joseph/git/irssi-sideways-split/src/core/signals.c:242:3
    #19 0x56416ca22996 in signal_emit_id /home/joseph/git/irssi-sideways-split/src/core/signals.c:304:3
    #20 0x56416c9aa82e in irc_parse_incoming_line /home/joseph/git/irssi-sideways-split/src/irc/core/irc.c:392:3
    #21 0x56416ca2242c in signal_emit_real /home/joseph/git/irssi-sideways-split/src/core/signals.c:242:3
    #22 0x56416ca22996 in signal_emit_id /home/joseph/git/irssi-sideways-split/src/core/signals.c:304:3
    #23 0x56416c9aaafa in irc_parse_incoming /home/joseph/git/irssi-sideways-split/src/irc/core/irc.c:413:3
    #24 0x56416ca01b03 in irssi_io_invoke /home/joseph/git/irssi-sideways-split/src/core/misc.c:51:3
    #25 0x7f3287b460bd in g_main_context_dispatch (/usr/lib/libglib-2.0.so.0+0x6b0bd)
    #26 0x7f3287b47f68  (/usr/lib/libglib-2.0.so.0+0x6cf68)
    #27 0x7f3287b47fad in g_main_context_iteration (/usr/lib/libglib-2.0.so.0+0x6cfad)
    #28 0x56416c940ddc in main /home/joseph/git/irssi-sideways-split/src/fe-text/irssi.c:329:3
    #29 0x7f3286a11f69 in __libc_start_main (/usr/lib/libc.so.6+0x20f69)
    #30 0x56416c8127e9 in _start (/home/joseph/git/irssi-sideways-split/src/fe-text/irssi+0x1067e9)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/joseph/git/irssi-sideways-split/src/fe-text/textbuffer-view.c:670:24 in textbuffer_view_set_default_indent
==28829==ABORTING
```

**Comment by josephbisch** [comment]
Reproducer:

Run the following:
```
echo ':0 PRIVMSG :0' | nc -l -p 6667
```

Then run irssi and enter the following commands:
```
/window new rs
/window rshrink -600
/window down
/connect localhost
```

**Comment by ailin-nemui** [comment]
is this fixed by #836 ?

**Comment by josephbisch** [comment]
I think so. At least the reproducer I posted above no longer causes a crash.
