### ISSUE TITLE
UAF on statusbar redraw when bitlbee_typing_notice.pl fails to load

### ISSUE THREAD

**Issue by dequis** [irssi/irssi#924]
Here's the error that makes it fail to load

```
23:13 -!- Irssi: Error in script bitlbee_typing_notice:
23:13 Can't use an undefined value as a HASH reference at /home/dx/.irssi/scripts/autorun/bitlbee_typing_notice.pl line 215.
```

That line is `my $tag = Irssi::active_server->{tag};` inside the `typing_notice` function which is likely called at initial load through these:

```
Irssi::statusbar_item_register('typing_notice', undef, 'typing_notice');
Irssi::statusbars_recreate_items();
```

Here's a crash I caught:

```

Thread 1 "irssi" received signal SIGSEGV, Segmentation fault.
statusbar_redraw_needed_items (bar=0x555555888e40) at statusbar.c:1016
1016    statusbar.c: No such file or directory.
(gdb) bt
#0  statusbar_redraw_needed_items (bar=0x555555888e40) at statusbar.c:1016
#1  statusbar_redraw_dirty () at statusbar.c:1041
#2  0x0000555555592bcd in dirty_check () at irssi.c:134
#3  0x000055555557906f in dirty_check () at irssi.c:343
#4  main (argc=<optimized out>, argv=<optimized out>) at irssi.c:343

(gdb) p tmp
$9 = 0x5555558895c0 = {0x21, 0x22, 0x23, 0x24, 0x6c, 0x1b, 0x1c, 0x1d}
```

That `0x5555558895c0` should be a member of `bar->items` over which it is iterating, but it seems to be gone. The other items look okay.

```
(gdb) p bar
$19 = (STATUSBAR_REC *) 0x555555888e40
(gdb) p *bar
$21 = {group = 0x55555578f6f0, config = 0x5555557801a0, parent_window = 0x5555558880b0, items = 0x5555558896b0 = {0x555555889030, 0x555555889320, 0x555555889700, 0x555555889bd0,
    0x555555889ca0, 0x555555889d10, 0x555555889d50, 0x55555588a200, 0x55555588a240, 0x55555588a280, 0x555555889100}, color = 0x555555888fd0 "%n%4%w", real_ypos = 53, dirty = 0,
  dirty_xpos = -1}
(gdb) p bar->items
$22 = 0x5555558896b0 = {0x555555889030, 0x555555889320, 0x555555889700, 0x555555889bd0, 0x555555889ca0, 0x555555889d10, 0x555555889d50, 0x55555588a200, 0x55555588a240, 0x55555588a280,
  0x555555889100}
(gdb) p bar->items->data
$23 = (gpointer) 0x555555889030
(gdb) p (SBAR_ITEM_REC *) bar->items->data
$24 = (SBAR_ITEM_REC *) 0x555555889030
(gdb) p *(SBAR_ITEM_REC *) bar->items->data
$25 = {bar = 0x555555888e40, config = 0x55555578f870, func = 0x555555587630 <statusbar_item_default_func>, min_size = 0, max_size = 0, xpos = 0, size = 0, current_size = 0, dirty = 0}
(gdb) p *(SBAR_ITEM_REC *) bar->items->next->data
$26 = {bar = 0x555555888e40, config = 0x55555578f890, func = 0x555555587630 <statusbar_item_default_func>, min_size = 8, max_size = 8, xpos = 0, size = 8, current_size = 8, dirty = 0}
(gdb) p *(SBAR_ITEM_REC *) bar->items->next->next->data
$27 = {bar = 0x555555888e40, config = 0x55555578f850, func = 0x555555587630 <statusbar_item_default_func>, min_size = 5, max_size = 5, xpos = 8, size = 5, current_size = 5, dirty = 0}
```

Here's some meaningless valgrind nonsense:

```
==7825== Invalid read of size 8
==7825==    at 0x13B4D0: ??? (in /home/dx/irssi/bin/irssi)
==7825==    by 0x7: ???
==7825==    by 0x961EB6A: ???
==7825==    by 0x80E49BF: ???
==7825==    by 0x742F6F5: ???
==7825==    by 0x6D: ???
==7825==    by 0xD2171C8CF1539BFF: ???
==7825==  Address 0x8c5e700 is 0 bytes inside a block of size 48 free'd
==7825==    at 0x4C2E10B: free (vg_replace_malloc.c:530)
==7825==    by 0x13C0CF: ??? (in /home/dx/irssi/bin/irssi)
==7825==    by 0x7DBF2EF: ???
==7825==  Block was alloc'd at
==7825==    at 0x4C2EEF5: calloc (vg_replace_malloc.c:711)
==7825==    by 0x56B1B21: g_malloc0 (in /usr/lib/libglib-2.0.so.0.5600.1)
==7825==    by 0x13B67F: ??? (in /home/dx/irssi/bin/irssi)
==7825==    by 0x7DBF2EF: ???
```

The connection between these errors and `bitlbee_typing_notice.pl` was a guess, but valgrind reliably caught this crap before and didn't catch anything after removing it.

So far I only reproduced this in my production instance and i'd prefer to not have to go through that ever again.

**Comment by ailin-nemui** [comment]
can you reproduce this? can you try this:

```
diff --git a/src/fe-text/statusbar.c b/src/fe-text/statusbar.c
index 40837eea..5b792254 100644
--- a/src/fe-text/statusbar.c
+++ b/src/fe-text/statusbar.c
@@ -1018,6 +1018,11 @@ static void statusbar_redraw_needed_items(STATUSBAR_REC *bar)
 		     rec->xpos >= bar->dirty_xpos)) {
 			rec->current_size = rec->size;
 			rec->func(rec, FALSE);
+			if (statusbar_need_recreate_items) {
+				/* we screwed up, script crashed? */
+				active_win = old_active_win;
+				return;
+			}
 			rec->dirty = FALSE;
 		}
 	}
```

**Comment by ailin-nemui** [comment]
@dequis

**Comment by dequis** [comment]
*snooze*
