### ISSUE TITLE
Uninitialized access in pos2scrpos (gui-entry.c)

### ISSUE THREAD

**Issue by dequis** [irssi/irssi#928]
Happened on terminal resize from phone-sized (83x46) to desktop-sized (239x62)

```
==8600== Conditional jump or move depends on uninitialised value(s)
==8600==    at 0x12D54D: ??? (in /home/dx/irssi/bin/irssi)
==8600==    by 0x9: ???
==8600==
==8600== (action on error) vgdb me ...
```

```
(gdb)
Thread 1 received signal SIGTRAP, Trace/breakpoint trap.
0x000000000012d54d in pos2scrpos (entry=entry@entry=0x8025ab0, pos=pos@entry=229, cursor=0) at gui-entry.c:222
222     gui-entry.c: No such file or directory.
(gdb) bt
#0  0x000000000012d54d in pos2scrpos (entry=entry@entry=0x8025ab0, pos=pos@entry=229, cursor=0) at gui-entry.c:222
#1  0x000000000012d906 in pos2scrpos (cursor=0, pos=229, entry=0x8025ab0) at gui-entry.c:336
#2  gui_entry_draw_from (pos=<optimized out>, entry=0x8025ab0) at gui-entry.c:337
#3  gui_entry_draw (entry=0x8025ab0) at gui-entry.c:427
#4  0x000000000013e520 in item_input (item=0x9cf2fc0, get_size_only=<optimized out>) at statusbar-items.c:443
#5  0x000000000013c1d5 in statusbar_redraw_needed_items (bar=0x7dbf270) at statusbar.c:1020
#6  statusbar_redraw_dirty () at statusbar.c:1041
#7  0x0000000000146bcd in dirty_check () at irssi.c:134
#8  0x000000000012d06f in dirty_check () at irssi.c:343
#9  main (argc=<optimized out>, argv=<optimized out>) at irssi.c:343
(gdb)
```

```
(gdb) info locals
c = 0
extent = 0x0
i = <optimized out>
xpos = 198
```

Had to tell vgdb to continue to not lose all my connections so I didn't get more details.

Code is at https://github.com/dequis/irssi/blob/dx/src/fe-text/gui-entry.c#L222

The currently pushed dx branch of my fork is master + most recent PRs merged:

```
19:52  * dx builds master + #896 + #914 + #917 + #919 + #922
```

Snippets from earlier conversation in #irssi:

```
23:23 <+Nei> entry is the thing where you type your messages
23:24 <+Nei> the loop runs from 0 to pos
23:24 <+Nei> I wonder how safe that is
23:24 <+dx> yeah i guess. the value of 'i' was optimized out, xpos is 198, i don't have entry
23:24 <+Nei> compare https://github.com/dequis/irssi/blob/dx/src/fe-text/gui-entry.c#L242
23:24 <+Not-irssi> L242:   for (i = 0; i < entry->text_len && xpos < pos; i++) {
```

```
23:26 <+Nei> maybe there was some implicit assumption that the pos must obviously be within existing text
23:26 <+Nei> but then the resize somehow screws that?
23:27 <+Nei> or it's been buggy all the time who knwos
23:28 <+dx> yeah this is the kind of bug that only appears once in a blue moon outside of valgrind
23:29 <+dx> i don't think i had anything in my input box
23:31 <+Nei> maybe just add the missing bounds check and be done with it?

**Comment by dequis** [comment]
FWIW i didn't have time to test #930 (and still really don't) but i've had crashes related to this issue (or maybe a different one) a couple of times this week, so i just upgraded that instance to current master and time will tell.
