### ISSUE TITLE
null pointer dereference in sk_value

### ISSUE THREAD

**Issue by ghost** [irssi/irssi#996]
This happened while using commit 9ec2c8cee4222c73229cffdf3c342e1f03be251f

    Program terminated with signal SIGSEGV, Segmentation fault.
    #0  0xacecaf77 in sk_value (st=0xacb31080, i=i@entry=0) at stack/stack.c:307
    307             return st->data[i];
    [Current thread is 1 (LWP 1)]
    (gdb) x/1i $eip
    => 0xacecaf77 <sk_value+23>:    mov    (%eax,%edx,4),%eax
    (gdb) i r eax edx
    eax            0x0      0
    edx            0x0      0
    (gdb) backtrace
    #0  0xacecaf77 in sk_value (st=0xacb31080, i=i@entry=0) at stack/stack.c:307
    #1  0xaced7808 in X509_STORE_get_by_subject (vs=vs@entry=0xbfb4f584, type=type@entry=1, name=name@entry=0xacb312c0, ret=ret@entry=0xbfb4f4e4) at x509/x509_lu.c:322
    #2  0xaced81ed in X509_STORE_CTX_get1_issuer (issuer=0xbfb4f554, ctx=0xbfb4f584, x=0xacbc7080) at x509/x509_lu.c:699
    #3  0xacedb5d7 in X509_verify_cert (ctx=ctx@entry=0xbfb4f584) at x509/x509_vfy.c:374
    #4  0xacf914e3 in ssl_verify_cert_chain (s=0xacbdb080, sk=0xacb312a0) at ssl_cert.c:406
    #5  0xacf949a8 in ssl3_get_server_certificate (s=s@entry=0xacbdb080) at ssl_clnt.c:1118
    #6  0xacf98d6e in ssl3_connect (s=0xacbdb080) at ssl_clnt.c:349
    #7  0xacf9d3b6 in SSL_connect (s=0xacbdb080) at ssl_lib.c:931
    #8  0x080eba9d in irssi_ssl_handshake (handle=handle@entry=0xacb4c1a0) at network-openssl.c:832
    #9  0x080e0787 in server_connect_callback_init_ssl (server=0xacb2f000, handle=0xacb4c1a0) at servers.c:176
    #10 0x080d872e in irssi_io_invoke (source=0xacb4c1a0, condition=G_IO_IN, data=data@entry=0xacb3dcb0) at misc.c:51
    #11 0xad200aa4 in g_io_unix_dispatch (source=source@entry=0xacbd9060, callback=0x80d86f0 <irssi_io_invoke>, user_data=0xacb3dcb0) at giounix.c:165
    #12 0xad1b68db in g_main_dispatch (context=0xacc29080, context@entry=0xacbd9060) at gmain.c:3191
    #13 g_main_context_dispatch (context=context@entry=0xacc29080) at gmain.c:3856
    #14 0xad1b6c65 in g_main_context_iterate (context=context@entry=0xacc29080, block=block@entry=1, dispatch=dispatch@entry=1,  self=<optimized out>) at gmain.c:3929
    #15 0xad1b6d42 in g_main_context_iteration (context=0xacc29080, context@entry=0x0, may_block=may_block@entry=1) at gmain.c:3990
    #16 0x080fc634 in main (argc=2, argv=0xbfb4f9f4) at irssi.c:346

Hrm.. I'm thinking this might be a bug in my ssl library now instead.

**Comment by dequis** [comment]
"my ssl library"? Is this not stock openssl? If it is, version?

**Comment by kkabrams** [comment]
ldd says irssi is linked to a build of libressl, but the backtrace is talking about openssl stuff.

**Comment by ailin-nemui** [comment]
please test with sane settings not  LD_PRELOAD hacks

**Comment by ailin-nemui** [comment]
Closing for inactivity
